# Generated by Django 5.2.8 on 2025-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20),
        ),
    ]
